# Generated by Django 4.2.4 on 2024-06-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
