# Generated by Django 4.1.2 on 2024-07-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referal', to='backend.profile'),
        ),
        migrations.CreateModel(
            name='Register_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registred_profile', to='backend.profile')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register', to='backend.referral')),
            ],
        ),
    ]
