# Generated by Django 4.1.2 on 2024-07-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_referral_profile_register_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-07-06 18:20:53'),
            preserve_default=False,
        ),
    ]
