# Generated by Django 4.1.2 on 2024-07-07 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_register_link_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
