# Generated by Django 4.1.2 on 2024-07-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_profiles', to='backend.referral'),
        ),
    ]
