# Generated by Django 4.1.2 on 2024-07-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_profile_recommended_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_link',
        ),
    ]
