# Generated by Django 4.1.2 on 2024-07-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_delete_register_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
