# Generated by Django 4.1.2 on 2024-07-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_referral_click_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='click_count',
        ),
        migrations.CreateModel(
            name='Click_Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referal_link', to='backend.referral')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
