# Generated by Django 4.1.2 on 2024-07-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_balance_profile_deposit_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='income_doxod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='income_oborot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
