# Generated by Django 4.1.2 on 2024-07-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_profile_income_doxod_profile_income_oborot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ftd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FTD', to='backend.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
