# Generated by Django 4.1.2 on 2024-07-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_ftd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftd',
            name='recommended_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rec', to='backend.profile'),
            preserve_default=False,
        ),
    ]
