# Generated by Django 4.1.2 on 2024-07-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_ftd_recommended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftd',
            name='recommended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='backend.profile'),
        ),
    ]
