# Generated by Django 4.2.4 on 2024-07-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_ftd_recommended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='withdraw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
