# Generated by Django 4.2.4 on 2024-07-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_profile_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
