# Generated by Django 4.1.2 on 2024-08-08 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_profile_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet_id', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='backend.profile')),
                ('type_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.wallet_type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
