# Generated by Django 4.1.2 on 2024-08-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_wallet_type_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
