# Generated by Django 4.1.2 on 2024-10-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_remove_userbroker_ref_broker_userbroker_uuid'),
        ('backend', '0024_alter_click_referral_created_at_alter_ftd_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_by_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_by_ref_profile', to='backend.profile')),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_by_ref', to='backend.referral')),
                ('user_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_by_ref_user_broker', to='broker.userbroker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
