# Generated by Django 4.2.4 on 2024-10-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_remove_userbroker_ref_broker_userbroker_uuid'),
        ('backend', '0026_remove_profile_recommended_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftd',
            name='profile',
        ),
        migrations.AddField(
            model_name='ftd',
            name='user_broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FTD', to='broker.userbroker'),
            preserve_default=False,
        ),
    ]
