# Generated by Django 4.1.2 on 2024-10-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_remove_register_by_ref_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_by_ref',
        ),
    ]
