# Generated by Django 4.2.4 on 2024-10-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_delete_register_by_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='type',
            field=models.CharField(choices=[('main', 'Главная страница '), ('register', ' Ссылка на регистрацию'), ('android', ' Ссылка на Android '), ('fast', ' Быстрый вход в платформу')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('doxod', 'Doxod'), ('oborot', 'Oborot')], max_length=20),
        ),
    ]
