# Generated by Django 4.2.4 on 2024-10-11 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_referral_type_alter_referral_referral_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_ref',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
