# Generated by Django 4.2.4 on 2024-10-11 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_profile_sub_ref_referral_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sub_ref',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
