# Generated by Django 4.2.4 on 2024-10-11 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_profile_sub_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sub_ref',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
