# Generated by Django 4.2.4 on 2024-10-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_profile_sub_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_by_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_by_ref_partner', to='backend.profile'),
        ),
    ]
