# Generated by Django 4.2.4 on 2024-10-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_profile_recommended_by_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('doxod', 'Доля дохода'), ('oborot', 'Доля оборота')], max_length=20),
        ),
    ]
