# Generated by Django 4.2.4 on 2024-10-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_referral_referral_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='deposit',
        ),
    ]
