# Generated by Django 4.2.4 on 2024-10-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_profile_deposit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('profile', 'type_wallet'), name='unique_profile_type_wallet'),
        ),
    ]
