# Generated by Django 4.1.2 on 2024-10-27 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_wallet_unique_profile_type_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_level',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
