# Generated by Django 4.2.4 on 2024-10-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_profile_next_level_alter_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='type',
            field=models.CharField(choices=[('main', 'Главная страница '), ('android', ' Ссылка на Android '), ('fast', ' Быстрый вход в платформу')], max_length=20),
        ),
    ]
