# Generated by Django 4.2.4 on 2024-12-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_referral_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_payment', to='backend.profile')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
