# Generated by Django 4.2.4 on 2026-01-13 11:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('promo_code', models.CharField(max_length=200, unique=True)),
                ('end_time', models.DateTimeField()),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(70)])),
                ('limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='backend.profile')),
                ('type_of_promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.type_promo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
