# Generated by Django 4.2.4 on 2026-01-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_type_promo_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(choices=[('level', 'Уровень'), ('register', 'Регистрация'), ('ftd', 'FTD')], max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('broker_user_id', models.BigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='backend.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
