# Generated by Django 4.2.4 on 2026-01-19 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_notifacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='name',
        ),
        migrations.CreateModel(
            name='Promo_activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_active', to='backend.promocode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
