# Generated by Django 4.2.4 on 2026-01-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_remove_promocode_name_promo_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='end_time',
            field=models.DateField(),
        ),
    ]
