# Generated by Django 4.2.4 on 2026-01-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0018_alter_userbroker_doxodnost'),
        ('backend', '0045_alter_promocode_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_activation',
            name='user_broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_activation_broker', to='broker.userbroker'),
        ),
        migrations.AlterField(
            model_name='notifacation',
            name='title',
            field=models.CharField(choices=[('level', 'Вы достигли новый уровень !'), ('register', 'У вас новый реферал !'), ('ftd', 'Реферал сделал первый депозит !')], max_length=20),
        ),
    ]
