# Generated by Django 4.1.2 on 2024-09-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_profile_first_name_remove_profile_last_name'),
        ('broker', '0005_userbroker_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbroker',
            name='token',
        ),
        migrations.AddField(
            model_name='userbroker',
            name='ref_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_broker', to='backend.referral'),
        ),
    ]
