# Generated by Django 4.1.2 on 2024-09-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_remove_userbroker_token_userbroker_ref_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbroker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
