# Generated by Django 4.2.4 on 2024-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_userbroker_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbroker',
            name='ref_broker',
        ),
        migrations.AddField(
            model_name='userbroker',
            name='uuid',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
