# Generated by Django 4.2.4 on 2024-10-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_remove_register_by_ref_profile'),
        ('broker', '0008_remove_userbroker_ref_broker_userbroker_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbroker',
            name='broker_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_by_ref_user_broker', to='backend.referral'),
        ),
    ]
