# Generated by Django 4.2.4 on 2024-10-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_userbroker_broker_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbroker',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
