# Generated by Django 4.2.4 on 2024-10-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_userbroker_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbroker',
            name='withdraw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
