# Generated by Django 4.2.4 on 2024-10-29 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0011_userbroker_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbroker',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userbroker',
            name='doxodnost',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AddField(
            model_name='userbroker',
            name='oborot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userbroker',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
