# Generated by Django 4.2.4 on 2025-10-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_userbroker_balance_userbroker_doxodnost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbroker',
            name='uuid',
        ),
    ]
