# Generated by Django 4.2.4 on 2025-10-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0013_remove_userbroker_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbroker',
            name='country_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbroker',
            name='nickname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
