# Generated by Django 4.2.4 on 2025-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0014_userbroker_country_code_userbroker_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbroker',
            name='broker_user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
