# Generated by Django 4.2.4 on 2025-12-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0015_userbroker_broker_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbroker',
            name='broker_user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
