# Generated by Django 4.2.4 on 2025-12-01 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0016_alter_userbroker_broker_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbroker',
            name='doxodnost',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
