# Generated by Django 4.2.4 on 2026-01-15 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0017_alter_userbroker_doxodnost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbroker',
            name='doxodnost',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
